"""Digest generation for RFP notifications."""

from datetime import datetime

from jinja2 import Template

from localizer.db import Database

DIGEST_TEMPLATE = Template("""\
Localizer RFP Digest — {{ now }}
{{ "=" * 60 }}

{{ rfps | length }} new opportunity(ies) found:

{% for rfp in rfps %}
{{ loop.index }}. [{{ rfp.source | upper }}] {{ rfp.title }}
   {% if rfp.due_date %}Due: {{ rfp.due_date }}{% endif %}
   {% if rfp.category %}Category: {{ rfp.category }}{% endif %}
   {% if rfp.estimated_value %}Est. Value: {{ rfp.estimated_value }}{% endif %}
   {% if rfp.url %}URL: {{ rfp.url }}{% endif %}
   {% if rfp.description %}{{ rfp.description[:200] }}{% if rfp.description|length > 200 %}...{% endif %}{% endif %}

{% endfor %}
---
Sources: {{ sources | join(", ") }}
""")

HTML_DIGEST_TEMPLATE = Template("""\
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, system-ui, sans-serif; max-width: 700px; margin: 0 auto; padding: 20px; }
  h1 { color: #1a1a1a; border-bottom: 2px solid #0066cc; padding-bottom: 10px; }
  .rfp { border: 1px solid #e0e0e0; border-radius: 8px; padding: 16px; margin: 12px 0; }
  .rfp h3 { margin: 0 0 8px 0; }
  .source { display: inline-block; background: #0066cc; color: white; padding: 2px 8px; border-radius: 4px; font-size: 12px; }
  .due { color: #cc0000; font-weight: bold; }
  .meta { color: #666; font-size: 14px; }
  a { color: #0066cc; }
</style>
</head>
<body>
<h1>Localizer RFP Digest</h1>
<p>{{ now }} &mdash; {{ rfps | length }} new opportunity(ies)</p>

{% for rfp in rfps %}
<div class="rfp">
  <span class="source">{{ rfp.source | upper }}</span>
  <h3>{% if rfp.url %}<a href="{{ rfp.url }}">{{ rfp.title }}</a>{% else %}{{ rfp.title }}{% endif %}</h3>
  <div class="meta">
    {% if rfp.due_date %}<span class="due">Due: {{ rfp.due_date }}</span> &bull; {% endif %}
    {% if rfp.category %}{{ rfp.category }} &bull; {% endif %}
    {% if rfp.estimated_value %}Est. Value: {{ rfp.estimated_value }}{% endif %}
  </div>
  {% if rfp.description %}<p>{{ rfp.description[:300] }}{% if rfp.description|length > 300 %}...{% endif %}</p>{% endif %}
</div>
{% endfor %}

<hr>
<p style="color: #999; font-size: 12px;">
  Sources: {{ sources | join(", ") }}<br>
  Generated by Localizer
</p>
</body>
</html>
""")


def generate_digest(db: Database, mark_notified: bool = True) -> tuple[str, str, list[dict]]:
    """Generate text and HTML digests for unnotified RFPs.

    Returns (text_digest, html_digest, rfps).
    """
    rfps = db.get_unnotified_rfps()
    if not rfps:
        return "", "", []

    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    sources = sorted(set(r["source"] for r in rfps))

    ctx = {"rfps": rfps, "now": now, "sources": sources}
    text = DIGEST_TEMPLATE.render(**ctx)
    html = HTML_DIGEST_TEMPLATE.render(**ctx)

    if mark_notified:
        db.mark_notified([r["id"] for r in rfps])

    return text, html, rfps
